
import { ServiceType } from "./types";

export const services: ServiceType[] = [
  {
    title: "Qualitative Data Insights Workshop",
    description: "Transform messy qualitative data into actionable business insights with AI-powered analysis techniques and custom processing workflows",
    price: "$2,499 per session",
    subtext: "Satisfaction Guaranteed",
    extraText: "Turn unstructured data into clear insights for faster decision making. Participants learn AI-powered analysis techniques and develop automated processes for ongoing data transformation.",
    features: [
      "Transform messy qualitative data into actionable insights",
      "Learn AI-powered analysis techniques and workflows", 
      "Develop automated data processing systems",
      "Extract clear patterns from unstructured information",
      "Includes pre-session data review and post-session templates",
    ],
    cta: "Learn More",
    secondaryCta: "Schedule a Consultation",
    calendlyLink: "https://calendly.com/gsdatwork/free-consult",
    learnMoreLink: "/qualitative-data-insights-workshop",
  },
  {
    title: "AI Action Workshop",
    description: "Quick win in a box: Transform what takes days or weeks into hours. Break your four-minute mile with AI and gain the know-how to replicate success across your organization",
    price: "$2,499 per session",
    subtext: "Satisfaction Guaranteed",
    extraText: "100-2000% efficiency gain for targeted tasks. Participants develop transferable SOPs, reduce cycle times, and maintain significantly higher energy levels throughout the workday.",
    features: [
      "Turn 2-day tasks into 2-hour victories with 10X transformation",
      "Learn to fish - gain skills to replicate success independently",
      "Create documented processes that spread success virally",
      "Break your four-minute mile - prove what's possible with AI",
      "Includes pre-session discovery and post-session support",
    ],
    cta: "Learn More",
    secondaryCta: "Schedule a Consultation",
    calendlyLink: "https://calendly.com/gsdatwork/free-consult",
    learnMoreLink: "/ai-action-workshop",
  },
  {
    title: "10x Effective Executive",
    description: "A 10-week AI-powered transformation program to accelerate productivity, reclaim time, and master AI tools that keep you ahead",
    price: "$9,999",
    subtext: "One-time engagement fee",
    extraText: "Cut email handling time by 50-80%, reclaim 10+ hours weekly for high-impact strategic work, and dramatically improve meeting quality with AI-enhanced preparation and follow-through.",
    features: [
      "Weekly 1:1 coaching sessions (50 minutes each)",
      "Personalized AI tool stack tailored to your needs",
      "Cut email handling time by 50-80%",
      "Amplify your authority with AI-powered content",
      "Measurable outcomes tied to your key results",
    ],
    cta: "Learn More",
    secondaryCta: "Schedule a Consultation",
    calendlyLink: "https://calendly.com/gsdatwork/10x-executive-consult",
    learnMoreLink: "/10x-executive",
  },
  {
    title: "Triple-A Transformation Program",
    description: "14-week program to revolutionize your operations with AI (Triple-A = Accelerated AI Adoption)",
    price: "Starting at $24,999 + Performance Incentives",
    subtext: "Pricing tied to measurable business outcomes",
    extraText: "Organization-wide efficiency gains leading to significant cost reduction, accelerated growth in new markets, greater velocity in delivering offerings, and elevated employee energy levels across teams.",
    features: [
      "Fractional Chief AI Officer services",
      "Comprehensive AI opportunity assessment",
      "Custom implementation roadmap",
      "Team training and change management",
      "ROI-focused metrics and tracking",
    ],
    cta: "Learn More",
    secondaryCta: "Schedule a Strategy Call",
    calendlyLink: "https://calendly.com/gsdatwork/free-consult",
    learnMoreLink: "/triple-a-transformation",
  },
];

export const valueMetrics = [
  "Immediate cost reduction (e.g., 30-40% on target processes)",
  "Direct revenue impact (e.g., 25%+ growth in target areas)",
  "Productivity gains (e.g., 3x faster execution on key tasks)",
  "Time saved (e.g., 15+ hours per week per team)",
  "ROI delivered (e.g., 5-10x return)",
];
