
import { ServiceType } from "./types";

export const services: ServiceType[] = [
  {
    title: "AI Oracle Session",
    description: "Transform executive decision-making with AI-powered organizational insights that integrate into your leadership cadence",
    price: "$2,499 per session",
    subtext: "Executive Intelligence System",
    extraText: "See what others miss. AI Oracle provides C-suite teams with strategic foresight, identifies hidden risks and opportunities, and becomes an ongoing participant in executive decision-making.",
    features: [
      "Gain unprecedented organizational visibility",
      "AI-powered strategic foresight and risk detection",
      "Operationalize into weekly executive syncs",
      "Interactive scenario testing and assumption validation",
      "Create data-driven organizational alignment",
    ],
    cta: "Learn More",
    secondaryCta: "Schedule Executive Briefing",
    calendlyLink: "https://calendly.com/gsdatwork/free-consult",
    learnMoreLink: "/ai-oracle-session",
  },
  {
    title: "AI Action Workshop",
    description: "Quick win in a box: Transform what takes days or weeks into hours. Break your four-minute mile with AI and gain the know-how to replicate success across your organization",
    price: "$2,499 per session",
    subtext: "Satisfaction Guaranteed",
    extraText: "100-2000% efficiency gain for targeted tasks. Participants develop transferable SOPs, reduce cycle times, and maintain significantly higher energy levels throughout the workday.",
    features: [
      "Turn 2-day tasks into 2-hour victories with 10X transformation",
      "Learn to fish - gain skills to replicate success independently",
      "Create documented processes that spread success virally",
      "Break your four-minute mile - prove what's possible with AI",
      "Includes pre-session discovery and post-session support",
    ],
    cta: "Learn More",
    secondaryCta: "Schedule a Consultation",
    calendlyLink: "https://calendly.com/gsdatwork/free-consult",
    learnMoreLink: "/ai-action-workshop",
  },
  {
    title: "10x Effective Executive",
    description: "A 10-week AI-powered transformation program for executives and their teams to accelerate productivity, reclaim time, and master AI tools organization-wide",
    price: "$19,999",
    subtext: "One-time engagement fee",
    extraText: "Transform your organization's productivity through executive leadership. Cut email handling time by 50-80%, reclaim 10+ hours weekly for strategic work, and create scalable AI systems that benefit your entire team.",
    features: [
      "5 bi-weekly coaching sessions (2 hours each)",
      "Team members welcome to join relevant sessions",
      "Personalized AI tool stack for your organization",
      "Cut email handling time by 50-80% across your team",
      "Build scalable AI processes that spread success",
      "Measurable outcomes tied to organizational results",
    ],
    cta: "Learn More",
    secondaryCta: "Schedule a Consultation",
    calendlyLink: "https://calendly.com/gsdatwork/10x-executive-consult",
    learnMoreLink: "/10x-executive",
  },
  {
    title: "Triple-A Transformation Program",
    description: "14-week program to revolutionize your operations with AI (Triple-A = Accelerated AI Adoption)",
    price: "Starting at $49,999 + Performance Incentives",
    subtext: "Pricing tied to measurable business outcomes",
    extraText: "Organization-wide efficiency gains leading to significant cost reduction, accelerated growth in new markets, greater velocity in delivering offerings, and elevated employee energy levels across teams.",
    features: [
      "Fractional Chief AI Officer services",
      "Comprehensive AI opportunity assessment",
      "Custom implementation roadmap",
      "Team training and change management",
      "ROI-focused metrics and tracking",
    ],
    cta: "Learn More",
    secondaryCta: "Schedule a Strategy Call",
    calendlyLink: "https://calendly.com/gsdatwork/free-consult",
    learnMoreLink: "/triple-a-transformation",
  },
];

export const valueMetrics = [
  "Immediate cost reduction (e.g., 30-40% on target processes)",
  "Direct revenue impact (e.g., 25%+ growth in target areas)",
  "Productivity gains (e.g., 3x faster execution on key tasks)",
  "Time saved (e.g., 15+ hours per week per team)",
  "ROI delivered (e.g., 5-10x return)",
];
